---
k8worker_marked_packages:
  # Placeholder

k8worker_packages:
  # Placeholder

k8worker_conflicting_packages:
  - docker.io

## TODO: Need to fix this
k8worker_ufw_rules:
  - proto: tcp
    port: "10250"
    name: "Kubernetes: Kubelet API"
  - proto: tcp
    port: "30000:32767"
    name: "NodePort Services"
