---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml
driver:
  name: docker
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # Skipped: containerd config modifications aren't idempotent
    - verify
    - cleanup
    - destroy
platforms:
  - name: k8control-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
    cgroupns_mode: host
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    host_vars:
      k8control-ubuntu2204:
        ansible_user: root
verifier:
  name: ansible
