---
- name: Restart postgresql
  ansible.builtin.systemd_service:
    name: postgresql
    state: restarted

- name: Reload postgresql
  ansible.builtin.systemd_service:
    name: postgresql
    state: reloaded
