---
galaxy_info:
  role_name: postgres
  namespace: bobmaertz
  author: Bob Maertz
  description: PostgreSQL bare metal installation
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies: []
