---
galaxy_info:
  role_name: general
  namespace: bobmaertz
  author: Bob Maertz
  description: General server configuration and security hardening
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies: []
