---
galaxy_info:
  role_name: k8common
  namespace: bobmaertz
  author: Bob Maertz
  description: Common Kubernetes node configuration
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies:
  - role: general
  - role: geerlingguy.containerd
