---
- name: Kubectl install Flannel
  ansible.builtin.command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  changed_when: false
  retries: 3
  delay: 5
