---
- name: Configure Kubernetes control plane nodes
  hosts: kcontrol
  become: true
  roles:
    - general
    - k8common
    - k8control

- name: Configure Kubernetes worker nodes
  hosts: kworker
  become: true
  roles:
    - general
    - k8common
