---
collections:
  - name: community.general
    version: ">=12.1.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  - name: geerlingguy.docker
    version: "7.4.7"
  - name: geerlingguy.containerd
    version: "1.3.1"
